### ISSUE TITLE
Homepage needs a link to signup page

### ISSUE THREAD

**Issue by hakanto** [funmusicplace/mirlo#452] opened 2024-01-03 20:43 UTC
_As a Visitor, I want to be able to sign up for Mirlo when I visit the homepage, so that I can use the service._

The current homepage -- https://mirlo.space/ -- does not have a path for a visitor to create a user account. A user can create a user account via https://mirlo.space/signup, however there is no link from https://mirlo.space/ to https://mirlo.space/signup.

This may be intentional, as y'all may want the initial userbase to be from communities that you've given the /signup link to. If not intentional, a link should be created.

**Comment by simonv3** [comment] 2024-01-03 21:40
This was intentional while we were doing things behind the scenes but this is a duplicate of #446 :)

**Closed by simonv3** 2024-01-03 21:40 UTC
