### ISSUE TITLE
Artwork is not included in zip-file when downloading

### ISSUE THREAD

**Issue by ksa618** [funmusicplace/mirlo#770] opened 2024-06-08 20:15 UTC
I've made my first purchase on Mirlo (https://mirlo.space/key13/release/misaligned-aardvarks), and just downloaded mp3 files. When downloading from Bandcamp the cover art is included in the zip file. I would like this from Mirlo as well.

**Comment by simonv3** [comment] 2024-06-09 21:12
Duplicate of #645

**Closed by simonv3** 2024-06-09 21:12 UTC
