### ISSUE TITLE
Improvement - Automatically include album artwork in downloadable archives

### ISSUE THREAD

**Issue by CPacaud123** [funmusicplace/mirlo#748] opened 2024-05-21 00:34 UTC
I just downloaded an album that had no embedded artwork and no "cover.jpg"-type file. I suggest considering automatically including the file uploaded as album artwork by the artist on album upload.

**Comment by simonv3** [comment] 2024-05-22 11:06
Duplicate of #645

**Closed by simonv3** 2024-05-22 11:06 UTC
