### ISSUE TITLE
Currency tag not working before payout

### ISSUE THREAD

**Issue by Cwpute** [funmusicplace/mirlo#816] opened 2024-08-20 09:33 UTC
It seems the {{currency}} tag in the string `nameYourPrice": "Name your price in {{ currency }}:"` doesn't work.
As you can see from the screenshot in #811, the currency doesn't align with that which is used in the string below the user-set price "93% of this amount (amount+currency) will go to…"

**Comment by Cwpute** [comment] 2024-08-20 09:39
Can also be seen here: https://mirlo.space/samnabi/release/sam-nabi-and-friends
![](url)

**Comment by simonv3** [comment] 2024-08-20 12:57
Duplicate of #810

**Closed by simonv3** 2024-08-20 12:57 UTC
