### ISSUE TITLE
Add Album / Artist page Custom Color Themes

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#118] opened 2023-10-15 11:44 UTC
Custom Theme Features : 

- Capacity for artists to change BG color and font color.
- Offer two color theme tabs : Light Theme / Dark Theme.

**Comment by simonv3** [comment] 2023-10-15 12:10
Duplicate of https://github.com/funmusicplace/mirlo/issues/98

**Closed by simonv3** 2023-10-15 12:10 UTC
